name: gupnet
channels:
  - pytorch
  - defaults   
dependencies:
  - pytorch=1.1.0 
  - torchvision=0.3.0 
  - cudatoolkit=9.0
  - python=3.6
  - tqdm
  - pyyaml
  - matplotlib
  - scikit-image
  - pip:
     - opencv-python